### ISSUE TITLE
ponto como separador de casas decimais nas bases

### ISSUE THREAD

**Issue by hslinhares** [splor-mg/sisor-dados#4]
as bases repasse e receita estão retornando valores com ponto como separador de milhar, assim o qlikview entende como texto.

**Comment by fjuniorr** [comment]
@hslinhares onde exatamente você achou separador de milhares? não encontrei em uma primeira verificação:

### Repasse

![image](https://github.com/splor-mg/sisor-dados/assets/4969445/5e5d6b2c-2e64-4433-800f-f9d9a1c65831)

-- https://raw.githubusercontent.com/splor-mg/sisor-dados-2024/main/data/base_repasse_recursos.csv

### Receita

![image](https://github.com/splor-mg/sisor-dados/assets/4969445/82c0e40a-866a-49b4-bae6-ef4f5fd1bcab)

-- https://raw.githubusercontent.com/splor-mg/sisor-dados-2024/main/data/base_orcam_receita_fiscal.csv
