### ISSUE TITLE
nomes de mesma variável diferentes entre bases.

### ISSUE THREAD

**Issue by hslinhares** [splor-mg/sisor-dados#5]
-  GRUPO_DE_DESPESA  e GRUPO_COD 
- FONTE e FONTE_COD, 
- IPU e IPU_COD, 
- IAG e IAG_COD 
- COD_UO e UO_COD

**Comment by fjuniorr** [comment]
Ótima observação @hslinhares. Pode abrir um PR nesse repo (ie. `sisor-dados`) sugerindo as alterações (ie. incluindo a propriedade `target` com os valores adequados do nome de cada coluna nos table schemas). 

Vamos padronizar nos nomes da base`base_qdd_fiscal` pra [harmonizar com o pacote execução da DCAF](https://github.com/splor-mg/cookiecutter-datapackage/issues/2).

**Comment by fjuniorr** [comment]
@hslinhares o PR splor-mg/sisor-dados-2024#1 tinha que ser no `sisor-dados`, e não no `sisor-dados-2024`.
